Repository ivancrg/vis.it, pull requests merged in 2021-05, with the labels that each got.

#50 Password hashing
  app/build.gradle
  app/src/main/java/com/example/visit/ChangePasswordFragment.java
  app/src/main/java/com/example/visit/LoginFragment.java
  app/src/main/java/com/example/visit/RegisterFragment.java
  app/src/main/java/com/example/visit/UserInterfaceFragment.java
  app/src/main/res/drawable/loading.gif
  app/src/main/res/layout/fragment_change_password.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_register.xml
  app/src/main/res/layout/fragment_user_interface.xml
Labels: enhancement

#62 Travelling weather to travelling screen
  app/src/main/java/com/example/visit/TravellingFragment.java
  app/src/main/java/com/example/visit/TravellingWeatherFragment.java
  app/src/main/res/drawable/ic_cloud.xml
  app/src/main/res/drawable/ic_sun.xml
  app/src/main/res/drawable/ic_weather_wait.xml
  app/src/main/res/drawable/rain.jpg
  app/src/main/res/drawable/snow.jpg
  app/src/main/res/drawable/sun.jpg
  app/src/main/res/drawable/sun_cloud.jpg
  app/src/main/res/drawable/weather_background.jpg
  app/src/main/res/layout/fragment_travelling_weather.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#63 Travelling music to travelling screen
  app/src/main/java/com/example/visit/CountryCityAPI.java
  app/src/main/java/com/example/visit/CountryPost.java
  app/src/main/java/com/example/visit/TravellingFragment.java
  app/src/main/java/com/example/visit/TravellingMusicFragment.java
  app/src/main/res/drawable/galaxy.jpg
  app/src/main/res/drawable/galaxy_music.png
  app/src/main/res/drawable/ic_baseline_fast_forward_24.xml
  app/src/main/res/drawable/ic_ff.xml
  app/src/main/res/drawable/ic_note2.xml
  app/src/main/res/drawable/ic_pause.xml
  app/src/main/res/drawable/ic_play.xml
  app/src/main/res/drawable/ic_rewind.xml
  app/src/main/res/layout/fragment_travelling_music.xml
  app/src/main/res/raw/test.mp3
  app/src/main/res/values/strings.xml
Labels: enhancement

#64 Travelling local time to travelling screen
  app/src/main/java/com/example/visit/TravellingFragment.java
  app/src/main/java/com/example/visit/TravellingTimeFragment.java
  app/src/main/res/layout/fragment_travelling_time.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#65 Trips screen
  app/build.gradle
  app/src/main/java/com/example/visit/ChosenTrip.java
  app/src/main/java/com/example/visit/MyTripsFragment.java
  app/src/main/java/com/example/visit/RecyclerViewAdapterMyTrips.java
  app/src/main/java/com/example/visit/RecyclerViewItemMyTrips.java
  app/src/main/java/com/example/visit/TripDetailsFragment.java
  app/src/main/java/com/example/visit/UserInterfaceFragment.java
  app/src/main/java/com/example/visit/database/HerokuAPI.java
  app/src/main/java/com/example/visit/database/TripsGet.java
  app/src/main/res/layout/fragment_my_trips.xml
  app/src/main/res/layout/fragment_trip_details.xml
  app/src/main/res/layout/fragment_user_interface.xml
  app/src/main/res/layout/my_trips_recycler_view_row.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#86 Sonar lint
  app/src/main/java/com/example/visit/MainActivity.java
  app/src/main/java/com/example/visit/SplashScreenActivity.java
  app/src/main/java/com/example/visit/database/CurrentTripGet.java
  app/src/main/java/com/example/visit/database/CurrentTripPatch.java
  app/src/main/java/com/example/visit/database/Database.java
  app/src/main/java/com/example/visit/database/RegisterPost.java
  app/src/main/java/com/example/visit/database/TripPost.java
  app/src/main/java/com/example/visit/database/TripsGet.java
  app/src/main/java/com/example/visit/database/UpdatePatch.java
  app/src/main/java/com/example/visit/planning/AccommodationFragment.java
  app/src/main/java/com/example/visit/planning/ChosenTrip.java
  app/src/main/java/com/example/visit/planning/CityFragment.java
  app/src/main/java/com/example/visit/planning/CountryFragment.java
  app/src/main/java/com/example/visit/planning/DateFragment.java
  app/src/main/java/com/example/visit/planning/ParticipantsFragment.java
  app/src/main/java/com/example/visit/planning/TravellingModeFragment.java
  app/src/main/java/com/example/visit/planning/TravellingNecessitiesFragment.java
  app/src/main/java/com/example/visit/planning/TripPlannerFragment.java
  app/src/main/java/com/example/visit/planning/TripPlanning.java
  app/src/main/java/com/example/visit/travelling/MyTripsFragment.java
  app/src/main/java/com/example/visit/travelling/RecyclerViewAdapterMyTrips.java
  app/src/main/java/com/example/visit/travelling/RecyclerViewItemMyTrips.java
  app/src/main/java/com/example/visit/travelling/TravellingFragment.java
  app/src/main/java/com/example/visit/travelling/TravellingMusicFragment.java
  app/src/main/java/com/example/visit/travelling/TravellingTimeFragment.java
  app/src/main/java/com/example/visit/travelling/TravellingWeatherFragment.java
  app/src/main/java/com/example/visit/travelling/TripDetailsFragment.java
  app/src/main/java/com/example/visit/user_profile/ChangePasswordFragment.java
  app/src/main/java/com/example/visit/user_profile/LoggedUser.java
  app/src/main/java/com/example/visit/user_profile/LoginFragment.java
  app/src/main/java/com/example/visit/user_profile/RegisterFragment.java
  app/src/main/java/com/example/visit/user_profile/UserInterfaceFragment.java
  app/src/main/java/com/example/visit/weather/OpenWeatherMap.java
  app/src/main/res/layout/fragment_change_password.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_register.xml
  app/src/main/res/layout/fragment_travelling.xml
  app/src/main/res/layout/fragment_trip_details.xml
  app/src/main/res/layout/fragment_trip_planner.xml
  app/src/main/res/layout/fragment_user_interface.xml
Labels: enhancement, fix

#87 Testing
  app/build.gradle
  app/src/androidTest/java/com/example/visit/CityCoordConversionTest.java
  app/src/main/assets/city_coordinates_conversion_test.csv
  app/src/main/java/com/example/visit/database/ConnectionTestResponse.java
  app/src/main/java/com/example/visit/database/DeleteTripResponse.java
  app/src/main/java/com/example/visit/database/HerokuAPI.java
  app/src/main/java/com/example/visit/database/TripPost.java
  app/src/main/java/com/example/visit/user_profile/RegisterFragment.java
  app/src/test/java/com/example/visit/DatabaseTests.java
  app/src/test/java/com/example/visit/ExampleUnitTest.java
  app/src/test/java/com/example/visit/RegisterFragmentTest.java
  app/src/test/resources/com/example/visit/database_connection_test.csv
  app/src/test/resources/com/example/visit/database_trip_insertion_test.csv
  app/src/test/resources/com/example/visit/register_validation_data.csv
Labels: enhancement, test
